[paths]
image_path = ./data/plate.jpg
csv_folder = ./colour_tables

[background]
; A: Цвет фона в формате R,G,B (например, белый)
color = 255,255,255
; A: Допуск для сравнения цвета (евклидово расстояние в RGB)
; R: Ещё не факт, что будет евклидово расстояние
tolerance = 15.0
